format_version: 3
pipelines:
  docker-dotnet-dojo:
    group: liget
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - "**/*.md"
    secure_variables:
      VAULT_TOKEN: "AES:KOIR+h5GSy/9N9ibBRFt7g==:wCLidBu4lvKkHPyLi+0912y1xnhfE3fTCWWWTNW+rFgep7ZpETYpchOxWuQ+d0Yf"
    stages:
      - verify:
          elastic_profile_id: w.c2.m2048.e20
          clean_workspace: true
          tasks:
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - ./tasks verify
      - build:
          clean_workspace: true
          elastic_profile_id: w.c2.m2048.e20
          jobs:
            stretch:
              resources:
                - docker_builder
              artifacts:
                - build:
                    source: "image/imagerc-stretch"
                    destination:
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_one stretch
            bionic:
              resources:
                - docker_builder
              artifacts:
                - build:
                    source: "image/imagerc-bionic"
                    destination:
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_one bionic
            full:
              resources:
                - docker_builder
              artifacts:
                - build:
                    source: "image/imagerc-full"
                    destination:
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_one full
            alpine:
              resources:
                - docker_builder
              artifacts:
                - build:
                    source: "image/imagerc-alpine"
                    destination:
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_one alpine
      - itest:
          clean_workspace: true
          jobs:
            stretch:
              elastic_profile_id: w.c2.m2048.e20
              tasks:
                - fetch:
                    stage: build
                    job: stretch
                    is_file: yes
                    source: imagerc-stretch
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest_one stretch
            bionic:
              elastic_profile_id: w.c2.m2048.e20
              tasks:
                - fetch:
                    stage: build
                    job: bionic
                    is_file: yes
                    source: imagerc-bionic
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest_one bionic
            full:
              elastic_profile_id: w.c2.m2048.e20
              tasks:
                - fetch:
                    stage: build
                    job: full
                    is_file: yes
                    source: imagerc-full
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest_one full
            alpine:
              elastic_profile_id: w.c2.m2048.e20
              tasks:
                - fetch:
                    stage: build
                    job: alpine
                    is_file: yes
                    source: imagerc-alpine
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks itest_one alpine
      - release:
          clean_workspace: true
          jobs:
            code:
              elastic_profile_id: w.c2.m2048.e20
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks release
      - publish:
          clean_workspace: true
          jobs:
            stretch:
              elastic_profile_id: w.c2.m2048.e20
              tasks:
                - fetch:
                    stage: build
                    job: stretch
                    is_file: yes
                    source: imagerc-stretch
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish_one stretch
            bionic:
              elastic_profile_id: w.c2.m2048.e20
              tasks:
                - fetch:
                    stage: build
                    job: bionic
                    is_file: yes
                    source: imagerc-bionic
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish_one bionic
            full:
              elastic_profile_id: w.c2.m2048.e20
              tasks:
                - fetch:
                    stage: build
                    job: full
                    is_file: yes
                    source: imagerc-full
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish_one full
            alpine:
              elastic_profile_id: w.c2.m2048.e20
              tasks:
                - fetch:
                    stage: build
                    job: alpine
                    is_file: yes
                    source: imagerc-alpine
                    destination: image/
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish_one alpine
