version: 2.1

workflows:
  # Environment variables required in CircleCI environment:
  #  - DOCKERHUB_USERNAME
  #  - DOCKERHUB_TOKEN
  docker-dotnet-dojo:
    jobs:
      - build_alpine
      - build_debian
      - verify_version
      - itest_alpine:
          requires:
            - build_alpine
      - itest_debian:
          requires:
            - build_debian
      - release:
          requires:
            - itest_alpine
            - itest_debian
            - verify_version
          filters:
            branches:
              only: master
      - publish_alpine:
          requires:
            - release
      - publish_debian:
          requires:
            - release

jobs:
  verify_version:
    executor: platform
    steps:
      - setup
      - run:
          command: /bin/bash -c "./tasks verify_version"

  build_alpine:
    executor: platform
    steps:
      - setup
      - run:
          command: /bin/bash -c "./tasks build alpine"
      - run:
          command: /bin/bash -c "./tasks push alpine"
      - persist_to_workspace:
          root: ~/repo
          paths:
            - image/imagerc-alpine

  build_debian:
    executor: platform
    steps:
      - setup
      - run:
          command: /bin/bash -c "./tasks build debian"
      - run:
          command: /bin/bash -c "./tasks push debian"
      - persist_to_workspace:
          root: ~/repo
          paths:
            - image/imagerc-debian

  itest_alpine:
    executor: platform
    steps:
      - setup
      - run:
          name: Install dojo
          command: |
            version="0.11.0"
            wget -O /tmp/dojo https://github.com/kudulab/dojo/releases/download/${version}/dojo_linux_amd64
            chmod +x /tmp/dojo
            sudo mv /tmp/dojo /usr/bin/dojo
      - run:
          command: sudo git clone https://github.com/bats-core/bats-core /opt/bats-core
      - run:
          command: sudo git clone https://github.com/bats-core/bats-assert /opt/bats-assert
      - run:
          command: sudo git clone https://github.com/bats-core/bats-support /opt/bats-support
      - attach_workspace:
          at: ~/repo
      - run:
          command: /bin/bash -c "./tasks itest alpine"

  itest_debian:
    executor: platform
    steps:
      - setup
      - run:
          name: Install dojo
          command: |
            version="0.11.0"
            wget -O /tmp/dojo https://github.com/kudulab/dojo/releases/download/${version}/dojo_linux_amd64
            chmod +x /tmp/dojo
            sudo mv /tmp/dojo /usr/bin/dojo
      - run:
          command: sudo git clone https://github.com/bats-core/bats-core /opt/bats-core
      - run:
          command: sudo git clone https://github.com/bats-core/bats-assert /opt/bats-assert
      - run:
          command: sudo git clone https://github.com/bats-core/bats-support /opt/bats-support
      - attach_workspace:
          at: ~/repo
      - run:
          command: /bin/bash -c "./tasks itest debian"

  release:
    executor: platform
    steps:
      - setup
      - run:
          command: /bin/bash -c "./tasks release"

  publish_alpine:
    executor: platform
    steps:
      - setup
      - attach_workspace:
          at: ~/repo
      - run:
          command: /bin/bash -c "./tasks publish alpine"

  publish_debian:
    executor: platform
    steps:
      - setup
      - attach_workspace:
          at: ~/repo
      - run:
          command: /bin/bash -c "./tasks publish debian"

commands:
  setup:
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            # generated with: ssh-keygen -t ed25519 -C "CircleCI to github.com"
            # then, public key added to github.com
            # and private key added to CircleCI
            - "21:2d:df:c0:2a:a6:b8:ba:0b:40:fd:93:b7:03:0d:33"

executors:
  platform:
    machine:
      image: ubuntu-2004:202101-01
    working_directory: ~/repo
